<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>第二十篇：Exception | Shane</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="#####1. 常见的异常处理结构

try/except
try/finally
raise
assert
with/as">
<meta property="og:type" content="article">
<meta property="og:title" content="第二十篇：Exception">
<meta property="og:url" content="http://mllover.com/2014/02/10/programing-language-python-learning-python-4-2014-02-09-ind020/index.html">
<meta property="og:site_name" content="Shane">
<meta property="og:description" content="#####1. 常见的异常处理结构

try/except
try/finally
raise
assert
with/as">
<meta property="og:updated_time" content="2014-02-12T14:26:42.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="第二十篇：Exception">
<meta name="twitter:description" content="#####1. 常见的异常处理结构

try/except
try/finally
raise
assert
with/as">
  
    <link rel="alternative" href="/atom.xml" title="Shane" type="application/atom+xml">
  
  
    <link rel="icon" href="/favicon.png">
  
  <link href="http://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="/css/style.css" type="text/css">
  <!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  

  

  

</head>
<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">Shane</a>
      </h1>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="../../../">Home</a>
        
          <a class="main-nav-link" href="/archives">Archives</a>
        
          <a class="main-nav-link" href="http://weibo.com/p/1005052133429541/home?from=page_100505&mod=TAB#place">Weibo</a>
        
      </nav>
      <nav id="sub-nav">
        
          <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="RSS Feed"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="Search"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" results="0" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="http://mllover.com"></form>
      </div>
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-programing-language-python-learning-python-4-2014-02-09-ind020" class="article article-type-post" itemscope itemprop="blogPost">
  <div class="article-meta">
    <a href="/2014/02/10/programing-language-python-learning-python-4-2014-02-09-ind020/" class="article-date">
  <time datetime="2014-02-10T13:51:08.000Z" itemprop="datePublished">Feb 10 2014</time>
</a>
    
  <div class="article-category">
    <a class="article-category-link" href="/categories/lerning-python-4/">lerning python 4</a>
  </div>

  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      第二十篇：Exception
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <p>#####1. 常见的异常处理结构</p>
<ul>
<li>try/except</li>
<li>try/finally</li>
<li>raise</li>
<li>assert</li>
<li>with/as<a id="more"></a>
#####2. 一些简单的例子<br>try/catch<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">fetcher</span><span class="params">(obj, index)</span>:</span></span><br><span class="line">    <span class="keyword">print</span> obj[index]</span><br><span class="line"></span><br><span class="line">a = [<span class="number">1</span>, <span class="number">2</span>, <span class="number">3</span>]</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    fetcher(a, <span class="number">3</span>)</span><br><span class="line"><span class="keyword">except</span> IndexError:</span><br><span class="line">    <span class="keyword">print</span> (<span class="string">'index error'</span>)</span><br><span class="line"><span class="keyword">print</span> (<span class="string">'continue'</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment">#result:</span></span><br><span class="line">index error</span><br><span class="line"><span class="keyword">continue</span></span><br></pre></td></tr></table></figure>
</li>
</ul>
<p>可以显式地raise,一般用于debugging。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> IndexError</span><br><span class="line"><span class="keyword">except</span> IndexError:</span><br><span class="line">    <span class="keyword">print</span> (<span class="string">'index error'</span>)</span><br></pre></td></tr></table></figure></p>
<p>可以自定义exception。一般继承自Exception或其它build-in异常类。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">doom</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">raise</span> Bad()</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    doom()</span><br><span class="line"><span class="keyword">except</span> Bad:</span><br><span class="line">    print(<span class="string">'got bad'</span>)</span><br></pre></td></tr></table></figure></p>
<p>try可以和finally连用。不管是不是有exception。finally都会被执行。这里有<strong>一点要注意</strong>:<br>当仅有try和finally没有exception时，发生了异常后，程序执行完finally后会向上传播异常，有可能导致后面的代码无法执行。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="prompt">&gt;&gt;&gt; </span><span class="function"><span class="keyword">def</span> <span class="title">after</span><span class="params">()</span>:</span></span><br><span class="line"><span class="prompt">... </span>    <span class="keyword">try</span>:</span><br><span class="line"><span class="prompt">... </span>        fetcher(x, <span class="number">4</span>)</span><br><span class="line"><span class="prompt">... </span>    <span class="keyword">finally</span>:</span><br><span class="line"><span class="prompt">... </span>        print(<span class="string">'after fetch'</span>)</span><br><span class="line"><span class="prompt">... </span>    print(<span class="string">'after try?'</span>)</span><br><span class="line">...</span><br><span class="line"><span class="prompt">&gt;&gt;&gt; </span>after()</span><br><span class="line">after fetch</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">3</span>, <span class="keyword">in</span> after</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">2</span>, <span class="keyword">in</span> fetcher</span><br><span class="line">IndexError: string index out of range</span><br></pre></td></tr></table></figure></p>
<p>所以finally语句里可以放一些释放资源的语句。</p>
<p>对于某些object可以使用with/as语句：<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="prompt">&gt;&gt;&gt; </span><span class="keyword">with</span> open(<span class="string">'lumberjack.txt'</span>, <span class="string">'w'</span>) <span class="keyword">as</span> file:        <span class="comment"># Always close file on exit</span></span><br><span class="line"><span class="prompt">... </span>    file.write(<span class="string">'The larch!\n'</span>)</span><br></pre></td></tr></table></figure></p>
<p>#####3. try/except/else<br>try寻找except的顺序是从上到下，从左到右。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run this main action first</span></span><br><span class="line"><span class="keyword">except</span> &lt;name1&gt;:</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run if name1 is raised during try block</span></span><br><span class="line"><span class="keyword">except</span> (name2, name3):</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run if any of these exceptions occur</span></span><br><span class="line"><span class="keyword">except</span> &lt;name4&gt; <span class="keyword">as</span> &lt;data&gt;:</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run if name4 is raised, and get instance raised</span></span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run for all (other) exceptions raised</span></span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    &lt;statements&gt;            <span class="comment"># Run if no exception was raised during try block</span></span><br></pre></td></tr></table></figure></p>
<p>#####4. raise<br><figure class="highlight"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">raise &lt;instance&gt;             # Raise instance of class</span><br><span class="line">raise &lt;class&gt;                # Make and raise instance of class</span><br><span class="line">raise                        # Reraise the most recent exception</span><br></pre></td></tr></table></figure></p>
<p>如果raise的是一个实例，那么 <code>except ExceptionName as X</code> 就派上用场了。X将会被赋予这个实例。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span><span class="params">(self, value)</span>:</span></span><br><span class="line">        self.x = value</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException(<span class="number">1</span>)</span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> X:</span><br><span class="line">    <span class="keyword">print</span> X.x  <span class="comment"># 1</span></span><br></pre></td></tr></table></figure></p>
<p>python3.0(not 2.6)还支持 <code>raise exception from otherexception</code>语法。exception会赋给otherexception的<code>__cause__</code>属性。otherexception会赋给exception的<code>__context__</code>属性。如果没有显示地catch这个异常，python打印exception的同时也会打印出导致这个异常的异常，即otherexception。</p>
<p>#####5. assert<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">assert</span> &lt;test&gt;, &lt;data&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">#和下面代码类似</span></span><br><span class="line"><span class="keyword">if</span> __debug__:  <span class="comment"># is build-in name = True if -0 flag is not used.</span></span><br><span class="line">	<span class="keyword">if</span> <span class="keyword">not</span> &lt;test&gt;:</span><br><span class="line">		<span class="keyword">raise</span> AssertionError(&lt;data&gt;)</span><br></pre></td></tr></table></figure></p>
<p>当<code>-0</code>命令符被使用时，assert会被编译程序移除。</p>
<p>#####6. with/as Context Managers<br>2.5使用这个功能需要添加如下代码：<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">from</span> __future__ <span class="keyword">import</span> with_statement</span><br></pre></td></tr></table></figure></p>
<p>with/as 类似于 try/finally。但是with/as有很多丰富的基于对象的特性。<br>比如文件操作可以这么使用<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> open(<span class="string">r'C:\misc\data'</span>) <span class="keyword">as</span> myfile:</span><br><span class="line">    <span class="keyword">for</span> line <span class="keyword">in</span> myfile:</span><br><span class="line">        print(line)</span><br><span class="line">        ...more code here...</span><br></pre></td></tr></table></figure></p>
<p>它与下面的代码类似：<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">myfile = open(<span class="string">r'C:\misc\data'</span>)</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">for</span> line <span class="keyword">in</span> myfile:</span><br><span class="line">        print(line)</span><br><span class="line">        ...more code here...</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    myfile.close()</span><br></pre></td></tr></table></figure></p>
<p>如果要自定义可以通过with/as来访问的类。可以通过<code>__enter__</code>和<code>__exit__</code>函数实现。下面是一个例子。<br><figure class="highlight"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line">class TraceBlock:</span><br><span class="line">    def message(self, arg):</span><br><span class="line">        print('running', arg)</span><br><span class="line">    def __enter__(self):</span><br><span class="line">        print('starting with block')</span><br><span class="line">        return self</span><br><span class="line">    def __exit__(self, exc_type, exc_value, exc_tb):</span><br><span class="line">        if exc_type is None:</span><br><span class="line">            print('exited normally\n')</span><br><span class="line">        else:</span><br><span class="line">            print('raise an exception!', exc_type)</span><br><span class="line">            return False                                  # Propagate</span><br><span class="line">with TraceBlock() as action:</span><br><span class="line">    action.message('test 1')</span><br><span class="line">    print('reached')</span><br><span class="line">with TraceBlock() as action:</span><br><span class="line">    action.message('test 2')</span><br><span class="line">    raise TypeError</span><br><span class="line">    print('not reached')</span><br><span class="line"></span><br><span class="line">#result:</span><br><span class="line">% python withas.py</span><br><span class="line">starting with block</span><br><span class="line">running test 1</span><br><span class="line">reached</span><br><span class="line">exited normally</span><br><span class="line">starting with block</span><br><span class="line">running test 2</span><br><span class="line">raise an exception! &lt;class 'TypeError'&gt;</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File "withas.py", line 20, in &lt;module&gt;</span><br><span class="line">    raise TypeError</span><br><span class="line">TypeError</span><br></pre></td></tr></table></figure></p>
<p>更多的细节，请见852页。</p>
<p>#####7. Exception Object<br>Python 2.5之前支持string类型的execption。但是在2.6和3.0以及之后就不再支持了。<br>raise时，如果我们传的是类而不是对象。Python会自动为我们创建一个没有构造函数参数的对象。<br>build-in对象的构造函数有一个string参数，可以自定义一些输出，比如：<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="prompt">&gt;&gt;&gt; </span><span class="keyword">raise</span> IndexError                    <span class="comment"># Same as IndexError(): no arguments</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">IndexError</span><br><span class="line"><span class="prompt">&gt;&gt;&gt; </span><span class="keyword">raise</span> IndexError(<span class="string">'spam'</span>)            <span class="comment"># Constructor argument attached, printed</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">IndexError: spam</span><br><span class="line"><span class="prompt">&gt;&gt;&gt; </span>I = IndexError(<span class="string">'spam'</span>)              <span class="comment"># Available in object attribute</span></span><br><span class="line"><span class="prompt">&gt;&gt;&gt; </span>I.args</span><br><span class="line">(<span class="string">'spam'</span>,)</span><br></pre></td></tr></table></figure></p>
<p>#####8. Designing with Exceptions<br>try/exception的嵌套是寻找最近层的except语句，执行完后继续except语句之后执行。<br>try/finally的嵌套，所有层finally都会执行。<br>下面是一个例子：<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">func</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span> Exception(<span class="string">'func'</span>)</span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">print</span> <span class="string">'func except'</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        <span class="keyword">print</span> <span class="string">'func finally'</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">print</span> <span class="string">'func continue'</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    func()</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    <span class="keyword">print</span> <span class="string">'main'</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">print</span> <span class="string">'func finally'</span></span><br></pre></td></tr></table></figure></p>
<p>#####9.sys.exc_info()记录了exceptin的消息，可以用它来获取异常类型。<br><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    ...run program...</span><br><span class="line"><span class="keyword">except</span>:                         <span class="comment"># All uncaught exceptions come here</span></span><br><span class="line">    <span class="keyword">import</span> sys</span><br><span class="line">    print(<span class="string">'uncaught!'</span>, sys.exc_info()[<span class="number">0</span>], sys.exc_info()[<span class="number">1</span>])</span><br><span class="line">	<span class="comment">#sys.exc_info通常在except使用</span></span><br></pre></td></tr></table></figure></p>
<p>sys.exc_info包含(type, value, traceback)</p>
<ul>
<li>type: exception class</li>
<li>value: exception class instance</li>
<li>traceback: call stack at the point where the exception originally occurred.</li>
</ul>
<p>#####10. 要避免使用空except。也就是<code>except: ...</code>这种结构。</p>

      
    </div>
    <footer class="article-footer">
      <a data-url="http://mllover.com/2014/02/10/programing-language-python-learning-python-4-2014-02-09-ind020/" data-id="cid5ozz0m000jq04d6nh3cvg4" class="article-share-link">Share</a>
      
        <a href="http://mllover.com/2014/02/10/programing-language-python-learning-python-4-2014-02-09-ind020/#disqus_thread" class="article-comment-link">Comments</a>
      
      
  <ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/language/">language</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/learning-python-4/">learning python 4</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/python/">python</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/study/">study</a></li></ul>

    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2014/02/11/tools-emacs-2014-02-11-ind001/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Newer</strong>
      <div class="article-nav-title">
        
          Emacs之基本操作
        
      </div>
    </a>
  
  
    <a href="/2014/02/10/gallery-2014-02-10-清晨-校园雪景/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Older</strong>
      <div class="article-nav-title">清晨校园雪景</div>
    </a>
  
</nav>

  
</article>


<section id="comments">
<!-- Duoshuo Comment BEGIN -->
	<div class="ds-thread"></div>
<script type="text/javascript">
var duoshuoQuery = {short_name:"shane"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = 'http://static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		|| document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- Duoshuo Comment END -->
</section>
</section>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2015 Shane Wang<br>
      <!--Powered by <a href="http://zespia.tw/hexo/" target="_blank">Hexo</a>-->
    </div>
  </div>
  
    
    <!-- mathjax config similar to math.stackexchange -->

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i=0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>

<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
  

</footer>
    </div>
    <nav id="mobile-nav">
  
    <a href="../../../" class="mobile-nav-link">Home</a>
  
    <a href="/archives" class="mobile-nav-link">Archives</a>
  
    <a href="http://weibo.com/p/1005052133429541/home?from=page_100505&mod=TAB#place" class="mobile-nav-link">Weibo</a>
  
</nav>
    
<script>
  var disqus_shortname = '1';
  
  var disqus_url = 'http://mllover.com/2014/02/10/programing-language-python-learning-python-4-2014-02-09-ind020/';
  
  (function(){
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//go.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>


<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


<link rel="stylesheet" href="/fancybox/jquery.fancybox.css" media="screen" type="text/css">
<script src="/fancybox/jquery.fancybox.pack.js"></script>


<script src="/js/script.js" type="text/javascript"></script>
  </div>
</body>
</html>